import type { Task } from "./taskTypes";

const now = Date.UTC(2026, 6, 15);
const day = 24 * 60 * 60 * 1000;

export const demoTasks: Task[] = [
  {
    id: "demo-task-brief",
    title: "Draft project brief",
    courseId: "studio_work",
    status: "in_progress",
    priority: "high",
    due: "2026-07-18",
    notes: "Outline goals, constraints, and next decisions.",
    durationHrs: 2,
    difficulty: 3,
    createdAt: now - day,
    mode: "task",
  },
  {
    id: "demo-task-review",
    title: "Review research notes",
    courseId: "design_research",
    status: "to_do",
    priority: "normal",
    due: "2026-07-22",
    notes: "Tag useful references and capture open questions.",
    durationHrs: 1.5,
    difficulty: 2,
    createdAt: now - 2 * day,
    mode: "task",
  },
  {
    id: "demo-task-prototype",
    title: "Prototype dashboard interaction",
    courseId: "client_project",
    status: "in_progress",
    priority: "high",
    due: "2026-07-16",
    notes: "Keep the first pass small and testable.",
    durationHrs: 3,
    difficulty: 4,
    createdAt: now - 3 * day,
    mode: "task",
  },
  {
    id: "demo-task-practice",
    title: "Practice presentation run-through",
    courseId: "practice",
    status: "to_do",
    priority: "normal",
    due: "2026-07-25",
    notes: "Time each section and mark rough transitions.",
    durationHrs: 1,
    difficulty: 2,
    createdAt: now - 4 * day,
    mode: "practice",
  },
  {
    id: "demo-task-done",
    title: "Collect sample references",
    courseId: "field_notes",
    status: "completed",
    priority: "low",
    due: "2026-07-14",
    notes: "Placeholder completed task for filtering and list views.",
    durationHrs: 1,
    difficulty: 1,
    createdAt: now - 5 * day,
    mode: "task",
  },
];
